# This is a basic workflow to help you get started with Actions
# https://github.com/marketplace/actions/azure-blob-storage-upload
name: Upload To UAT solution collections
on:
  push:
      branches: [ main ]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          #connection_string: 'DefaultEndpointsProtocol=https;AccountName=datarepo12;AccountKey=BUsE2RdEEiSMXqxTlGe7VG/IgpIXtDJgPWZc1HmmLpSyFGsomPYHynWpgN1i7IHnZO8Sq9JoDd4UFgCKd+9yFA==;EndpointSuffix=core.windows.net'
          account_name: 'testsolutionrepos'
          sas_token: 'sv=2020-08-04&se=2022-09-28T05%3A13%3A01Z&sr=c&sp=racwdxlt&sig=ic5KPaeGFqlAlssjtf8Zw%2BikdFhfJFUxjCGmktguqSQ%3D'
          container_name: 'loome-software'
          source_dir: 'dist'
